Update version of Gradle and libraries
oxeanbits/parsecs-android pull request #29
Opened 2023-10-30 19:02 UTC by krysthianlessa

This PR aims to upgrade the gradle version, and also the libraries used in the project. The table below shows the upgrades:

| Artifact | Old version | New version |
| --------- | -------------- | ---------------- |
| Gradle |  `6.7.1` | `7.5` |
| Kotlin |  `1.5.31` | `1.9.10` |
| Android SDK |  `30` | `33` |
| android-gradle-plugin |  `4.2.2` | `7.4.2 |
| appcompat |  `1.3.1` | `1.6.1` |
| constraintlayout |  `2.1.2` | `2.1.4` |
| junit |  `1.1.3` | `1.1.5` |
| espresso-core |  `3.4.0` | `3.5.1` |

2023-10-31 14:22 UTC, Marinofull commented
The CodeQL failure has no relations with this PR, see https://github.com/oxeanbits/parsecs-android/actions
![image](https://github.com/oxeanbits/parsecs-android/assets/4636436/ab9c14ca-39cd-4b4e-a674-a3759a804dfb)

2023-10-31 20:22 UTC, Marinofull commented on demo/src/main/java/br/com/nvsistemas/parsec/demo/MainActivity.kt
> +            binding.result2.text = eval(binding.expression2.text.split(",").map { it.trim() })
@rodiguif can you review if we can proceed to merge it all?

2023-11-01 04:55 UTC, rodiguif requested changes
Worked well! Also tested in DPMS. :no_smoking:  :heavy_check_mark:
Good job, dude!

We just need to better document some of these changes:

2023-11-01 04:55 UTC, rodiguif commented on demo/src/main/java/br/com/nvsistemas/parsec/demo/MainActivity.kt
> +        setContentView(binding.root)
Interesting :thinking: 

Could you explain better these changes in the description?

2023-11-01 04:55 UTC, rodiguif commented on demo/build.gradle
> +    }
Same here.

2023-11-01 13:05 UTC, merged